---
title: "Data exploratie"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output: 
  html_document:
      code_folding: hide
      toc: true
      toc_float: true
      toc_collapsed: true
      df_print: paged
  editor_options:
      chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
opts_knit$set(root.dir = here::here())

library(tidyverse)
library(sf)

source(here("src", "R", "functions.R"))
```


# Doel

Exploratie van de waarnemingendata na selectie en preparatie.


# Data inlezen

We lezen de waarnemingendata in van Slak-in-Du na data selectie en preparatie.

```{r}
# Locatie van data en output mappen
data_path <- here("data", "raw")
out_path <- here("data", "processed")

# Referentie coordinatensysteem: UTM zone 31N
proj_crs <- 32631

# Laad data
slakken_data <- read_csv(paste(out_path, "waarnemingen_kust.csv", sep = "/"))

# Zet om naar sf object
slakken_data_sf <- slakken_data %>% 
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)

# Zet crs om naar project crs
slakken_data_sf <- slakken_data_sf %>%
  st_transform(crs = proj_crs)

# Voeg buffer toe
slakken_data_sf_buffer <- slakken_data_sf %>%
  st_buffer(slakken_data_sf$precisie)
```


# Enkele cijfers


# Samenvattende tabel

Overzicht welke soorten in welk hok en welke toestand.

maak aparte functie met output cf bezoeken: get_visit_stats

```{r}
soortenlijst <- slakken_data %>%
  arrange(class, family, wet_soortnaam) %>%
  distinct(ned_soortnaam) %>%
  pull(ned_soortnaam)

test <- lapply(soortenlijst, function(i) {
  count_df <- stats_utm_grid(data = slakken_data_sf_buffer, soortnaam = i, 
                             resolutie = 10) %>%
    st_drop_geometry()
  
  counts <- count_df %>%
    count(occurrence) %>% 
    filter(!is.na(occurrence))
  
  tags <- count_df %>% 
    filter(occurrence == "aanwezig") %>% 
    arrange(TAG) %>% 
    pull(TAG)
  
  aanwezig <- counts[counts$occurrence == "aanwezig", "n"]
  afwezig <- counts[counts$occurrence == "afwezig", "n"]
  
  list(i, aanwezig / (aanwezig + afwezig), paste0(tags, collapse = ", "))
})

df <- do.call(what = rbind.data.frame, args = test)
names(df) <- c("ned_soortnaam", "prop_utm", "utm_hokken")

df %>% arrange(desc(prop_utm)) %>%
  kable()

hist(df$prop_utm)
```

